HospitalManagementSystem_MVCProject/Controllers/DoctorController.cs
using BusinessLayer.Interfaces;
using CommonLayer.Models;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;

namespace HospitalManagementSystem_MVCProject.Controllers
{
    public class DoctorController : Controller
    {
        private readonly IDoctorBusiness doctorBusiness;
        public DoctorController(IDoctorBusiness doctorBusiness)
        {
            this.doctorBusiness = doctorBusiness;
        }


        public IActionResult Index()
        {
            return View();
        }

        [HttpGet]
        public IActionResult AddDoctor()
        {
            return View();
        }

        [HttpPost]
        public IActionResult AddDoctor(Doctor doctor)
        {
            var res = doctorBusiness.AddDoctor(doctor);
            if (res)
                return RedirectToAction("GetAllDoctors");
            return View(doctor);
        }


        [HttpGet]
        public IActionResult GetAllDoctors()
        {
            List<Doctor> doctorsList = new List<Doctor>();
            doctorsList = doctorBusiness.GetAllDoctors().ToList();
            if (doctorsList != null)
            {
                //foreach(Doctor doctor in doctorsList)
                //{
                //    int DoctorId = doctor.DoctorId;
                //    HttpContext.Session.SetInt32("DoctorId", DoctorId);
                //}
                return View(doctorsList);
            }
            return View("Index");
        }

        [HttpGet]
        //[Route("GetById/{doctorId}")]
        public IActionResult GetDoctorById(int doctorId)
        {
            if (doctorId != null)
            {
                Doctor doctor = doctorBusiness.GetDoctorById(doctorId);
                if (doctor != null)
                {
                    HttpContext.Session.SetInt32("DoctorId", doctor.DoctorId);
                    return View(doctor);
                }
                else
                    return NotFound("Doctor not found for requested id: " + doctorId);
                //return NotFound();
            }
            else
                return NotFound();
        }

        [HttpGet]
        //[Route("UpdateById/{id}")]
        public IActionResult UpdateDoctor(int id)
        {
            if (id == null)
                return NotFound("Please provide doctorId");
            Doctor doctor = doctorBusiness.GetDoctorById(id);
            if (doctor == null)
                return NotFound("Doctor not found for requested id: " + id);
            return View(doctor);
        }

        [HttpPost]
        public IActionResult UpdateDoctor(int id, Doctor doctor)
        {
            if (id != doctor.DoctorId)
                return NotFound("Mismatch id");
            bool result = doctorBusiness.UpadateDoctor(doctor);
            if (result)
                return RedirectToAction("GetAllDoctors");
            return View(doctor);
        }

        [HttpGet]
        public IActionResult DeleteDoctor(int id)
        {
            if (id == null || id == 0)
                return NotFound("Please pass id");
            Doctor doctor = doctorBusiness.GetDoctorById(id);
            if (doctor == null)
                return NotFound("Doctor not found ford requested id: " + id);
            return View(doctor);
        }

        [HttpPost, ActionName("DeleteDoctor")]
        [ValidateAntiForgeryToken]
        public IActionResult ConfirmDeleteDoctor(int id)
        {
            if (id == 0)
                return View("index");
            bool result = doctorBusiness.DeleteDoctor(id);

            if (result) return RedirectToAction("GetAllDoctors");
            return NotFound("Failed to delet");
        }

        [HttpGet]
        public IActionResult DoctorLogin()
        {
            return View();
        }

        [HttpPost]
        public IActionResult DoctorLogin(LoginModel loginModel)
        {
            var doctor = doctorBusiness.DoctorLogin(loginModel);
            if (doctor != null)
            {
                HttpContext.Session.SetInt32("DoctorId", doctor.DoctorId);
                return RedirectToAction("GetDoctorById", new { doctorId = doctor.DoctorId });
            }
            return NotFound("Failed to login b/z invalid credentials");
        }


    }
}

HospitalManagementSystem_MVCProject/Controllers/PatientController.cs
using BusinessLayer.Interfaces;
using CommonLayer.Models;
using Microsoft.AspNetCore.Mvc;

namespace HospitalManagementSystem_MVCProject.Controllers
{
    public class PatientController : Controller
    {
        private readonly IPatientBusiness patientBusiness;
        public PatientController(IPatientBusiness patientBusiness)
        {
            this.patientBusiness = patientBusiness;
        }
        public IActionResult Index()
        {
            return View();
        }

        [HttpGet]
        public IActionResult RegisterPatient()
        {
            return View();
        }

        [HttpPost]
        public IActionResult RegisterPatient(Patient patient)
        {
            var result = patientBusiness.RegisterPatient(patient);
            if (result)
                return RedirectToAction("GetAllPatients");
            return View(patient);
        }

        [HttpGet]
        public IActionResult GetAllPatients()
        {
            var patients = patientBusiness.GetAllPatients().ToList();
            foreach(Patient patient in patients)
            {
                int PatientId = patient.PatientId;
                HttpContext.Session.SetInt32("PatientId", PatientId);
            }
            return View(patients);
        }

        [HttpGet]
        public IActionResult GetPatientById(int patientId)
        {
            if (patientId == null || patientId == 0)
                return NotFound("Patient id may be null or zero");
            Patient patient = patientBusiness.GetPatientById(patientId);
            if (patient == null)
                return NotFound("Patient not found for requested id: " + patientId);
            return View(patient);
        }

        [HttpGet]
        public IActionResult UpdatePatient(int id)
        {
            if (id == null || id == 0)
                return NotFound("Patient id may be null or zero, id: " + id);
            Patient patient = patientBusiness.GetPatientById(id);
            if (patient == null)
                return NotFound("Patient not found for id: " + id);
            return View(patient);
        }

        [HttpPost]
        public IActionResult UpdatePatient(int id, Patient patient)
        {
            if (id != patient.PatientId)
                return NotFound("Missmatch id");
            bool result = patientBusiness.UpdatePatient(patient);
            if (!result) return NotFound("Failed to update patient");
            else return RedirectToAction("GetAllPatients"); 
        }

        [HttpGet]
        public IActionResult DeletePatient(int patientId)
        {
            if (patientId == null || patientId == 0)
                return NotFound("Patient id may be null or zero, id: " + patientId);
            Patient patient = patientBusiness.GetPatientById(patientId);
            if (patient == null)
                return NotFound("Patient not found for id: " + patientId);
            return View(patient);
        }

        [HttpPost, ActionName("DeletePatient")]
        public IActionResult ConfirmDeletePatient(int patientId)
        {
            bool result = patientBusiness.DeletePatient(patientId);
            if (!result) return NotFound("Failed to delete patient");
            else return RedirectToAction("GetAllPatients");
        }

        [HttpGet]
        public IActionResult PatientLogin()
        {
            return View();
        }


        [HttpPost]
        public IActionResult PatientLogin(LoginModel loginModel)
        {
            if (loginModel.UserId == 0 || loginModel.UserName == null)
                return BadRequest("Please provide all credentials");
            Patient patient = patientBusiness.PatientLogin(loginModel);
            if (patient != null)
            {
                HttpContext.Session.SetInt32("PatientId", patient.PatientId);
                return RedirectToAction("GetPatientById", new { patientId = patient.PatientId });
            }
            else return NotFound("Invalid credentials");
        }

        


    }
}

HospitalManagementSystem_MVCProject/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - HospitalManagementSystem_MVCProject</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/NavbarStyleSheet.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/HospitalManagementSystem_MVCProject.styles.css" asp-append-version="true" />

    <link rel="stylesheet" href="~/css/NavbarStyleSheet.css" asp-append-version="true" />

</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">HospitalManagementSystem_MVCProject</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>

                        <li class="nav-item">
                            <a id="login-link" class="nav-link text-dark" asp-area="" asp-controller="Doctor" asp-action="DoctorLogin">Doctor</a>
                        </li>
                        <li class="nav-item">
                            <a id="login-link" class="nav-link text-dark" asp-area="" asp-controller="Patient" asp-action="PatientLogin">Patient</a>
                        </li>

                    </ul>

                </div>

            </div>
        </nav>
    </header>
    @* <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div> *@
     <div id="center-body">
        @RenderBody()
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - HospitalManagementSystem_MVCProject - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>