HospitalManagementSystem_MVCProject/Controllers/AppointmentController.cs
using BusinessLayer.Interfaces;
using CommonLayer.Models;
using Microsoft.AspNetCore.Mvc;

namespace HospitalManagementSystem_MVCProject.Controllers
{
    public class AppointmentController : Controller
    {
        private readonly IAppointmentBusiness appointmentBusiness;
        public AppointmentController(IAppointmentBusiness appointmentBusiness)
        {
            this.appointmentBusiness = appointmentBusiness;
        }

        public IActionResult Index()
        {
            return View();
        }

        [HttpGet]
        public IActionResult BookAppointment()
        {
            return View();
        }

        [HttpPost]
        public IActionResult BookAppointment(AppointmentModel appointmentModel)
        {
            // Below both will work
            if (appointmentModel.PatientId == 0 || appointmentModel.DoctorId == 0) return NotFound("NotFound: Please provide required id's");
            //if (appointmentModel.PatientId == 0 || appointmentModel.DoctorId == 0) return BadRequest("BadRequest: Please provide required id's");

            // Below both will not work b/z comparing int to null
            //if (appointmentModel.PatientId == null || appointmentModel.DoctorId == null) return BadRequest("BadRequest: Please provide required id's");
            //if (appointmentModel.PatientId == null || appointmentModel.DoctorId == null) return NotFound("NotFound: Please provide required id's");

            if (appointmentModel.ConcernAbout == null) return BadRequest("Please provide ConcernAbout");

            bool result = appointmentBusiness.BookAppointment(appointmentModel);
            if (!result) 
                return NotFound("Failed to book appointment");
            return RedirectToAction("GetAllAppointments");
        }

        [HttpGet]
        public IActionResult GetAllAppointments()
        {
            List<AppointmentModel> appointments = appointmentBusiness.GetAllAppointments().ToList();
            if (appointments == null) return NotFound("Failed to find appointments list");
            return View(appointments);
        }

        [HttpGet]
        public IActionResult GetAll()
        {
            var appointments = appointmentBusiness.GetAllAppointments().ToList();
            if (appointments == null) return NotFound("Failed to find appointments list");
            return View(appointments);
        }


        [HttpGet]
        public IActionResult PatientDoctorDetails()
        {
            List<AppointmentPatientModel> result = appointmentBusiness.PatientDetailsWithAppointedDoctor();
            return View(result);
        }


    }
}

HospitalManagementSystem_MVCProject/Controllers/DoctorController.cs
using BusinessLayer.Interfaces;
using CommonLayer.Models;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;

namespace HospitalManagementSystem_MVCProject.Controllers
{
    public class DoctorController : Controller
    {
        private readonly IDoctorBusiness doctorBusiness;
        public DoctorController(IDoctorBusiness doctorBusiness)
        {
            this.doctorBusiness = doctorBusiness;
        }


        public IActionResult Index()
        {
            return View();
        }

        [HttpGet]
        public IActionResult AddDoctor()
        {
            return View();
        }

        [HttpPost]
        public IActionResult AddDoctor(Doctor doctor)
        {
            var res = doctorBusiness.AddDoctor(doctor);
            if (res)
                return RedirectToAction("GetAllDoctors");
            return View(doctor);
        }


        [HttpGet]
        public IActionResult GetAllDoctors()
        {
            List<Doctor> doctorsList = new List<Doctor>();
            doctorsList = doctorBusiness.GetAllDoctors().ToList();
            if (doctorsList != null)
            {
                //foreach(Doctor doctor in doctorsList)
                //{
                //    int DoctorId = doctor.DoctorId;
                //    HttpContext.Session.SetInt32("DoctorId", DoctorId);
                //}
                return View(doctorsList);
            }
            return View("Index");
        }

        [HttpGet]
        //[Route("GetById/{doctorId}")]
        public IActionResult GetDoctorById(int doctorId)
        {
            if (doctorId != null)
            {
                Doctor doctor = doctorBusiness.GetDoctorById(doctorId);
                if (doctor != null)
                {
                    HttpContext.Session.SetInt32("DoctorId", doctor.DoctorId);
                    return View(doctor);
                }
                else
                    return NotFound("Doctor not found for requested id: " + doctorId);
                //return NotFound();
            }
            else
                return NotFound();
        }

        [HttpGet]
        //[Route("UpdateById/{id}")]
        public IActionResult UpdateDoctor(int id)
        {
            if (id == null)
                return NotFound("Please provide doctorId");
            Doctor doctor = doctorBusiness.GetDoctorById(id);
            if (doctor == null)
                return NotFound("Doctor not found for requested id: " + id);
            return View(doctor);
        }

        [HttpPost]
        public IActionResult UpdateDoctor(int id, Doctor doctor)
        {
            if (id != doctor.DoctorId)
                return NotFound("Mismatch id");
            bool result = doctorBusiness.UpadateDoctor(doctor);
            if (result)
                return RedirectToAction("GetAllDoctors");
            return View(doctor);
        }

        [HttpGet]
        public IActionResult DeleteDoctor(int id)
        {
            if (id == null || id == 0)
                return NotFound("Please pass id");
            Doctor doctor = doctorBusiness.GetDoctorById(id);
            if (doctor == null)
                return NotFound("Doctor not found ford requested id: " + id);
            return View(doctor);
        }

        [HttpPost, ActionName("DeleteDoctor")]
        [ValidateAntiForgeryToken]
        public IActionResult ConfirmDeleteDoctor(int id)
        {
            if (id == 0)
                return View("index");
            bool result = doctorBusiness.DeleteDoctor(id);

            if (result) return RedirectToAction("GetAllDoctors");
            return NotFound("Failed to delet");
        }

        [HttpGet]
        public IActionResult DoctorLogin()
        {
            return View();
        }

        [HttpPost]
        public IActionResult DoctorLogin(LoginModel loginModel)
        {
            var doctor = doctorBusiness.DoctorLogin(loginModel);
            if (doctor != null)
            {
                HttpContext.Session.SetInt32("DoctorId", doctor.DoctorId);
                return RedirectToAction("GetDoctorById", new { doctorId = doctor.DoctorId });
            }
            return NotFound("Failed to login b/z invalid credentials");
        }


    }
}

HospitalManagementSystem_MVCProject/Views/Doctor/AddDoctor.cshtml
@model CommonLayer.Models.Doctor

@{
    ViewData["Title"] = "AddDoctor";
}

<link rel="stylesheet" href="~/css/UserLoginStyleSheet.css" asp-append-version="true" />

<h1>Doctor Registration</h1>
<hr id="hr" />
@* <h4>Doctor</h4>
<hr /> *@
<div class="row">
    <div class="col-md-4">
        <form asp-action="AddDoctor">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            @* <div class="form-group">
                <label asp-for="DoctorId" class="control-label"></label>
                <input asp-for="DoctorId" class="form-control" />
                <span asp-validation-for="DoctorId" class="text-danger"></span>
            </div> *@
            <div class="form-group">
                <label asp-for="FullName" class="control-label"></label>
                <input asp-for="FullName" placeholder="FullName" class="form-control" />
                <span asp-validation-for="FullName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Email" class="control-label"></label>
                <input asp-for="Email" class="form-control" />
                <span asp-validation-for="Email" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Contact" class="control-label"></label>
                <input asp-for="Contact" class="form-control" type="tel" />
                <span asp-validation-for="Contact" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DOB" class="control-label"></label>
                <input asp-for="DOB" class="form-control" />
                <span asp-validation-for="DOB" class="text-danger"></span>
            </div>
            @* <div class="form-group">
                <label asp-for="Age" class="control-label"></label>
                <input asp-for="Age" class="form-control" />
                <span asp-validation-for="Age" class="text-danger"></span>
            </div> *@
            <div class="form-group">
                <label asp-for="Gender" class="control-label"></label>
                @* <input asp-for="Gender" class="form-control" /> *@

                <div class="form-group" id="radio-btn" >
                    @Html.RadioButtonFor(m => m.Gender, "Male") Male
                    @Html.RadioButtonFor(m => m.Gender, "Female") Female
                </div>

                <span asp-validation-for="Gender" class="text-danger"></span>

            </div>
            <div class="form-group">
                <label asp-for="Qualification" class="control-label"></label>
                <input asp-for="Qualification" class="form-control" />
                <span asp-validation-for="Qualification" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Specialization" class="control-label"></label>
                @* <input asp-for="Specialization" class="form-control" /> *@

                <select asp-for="Specialization" class="form-control">
                    <option hidden > --- Select ---</option>
                    <option value="Cardiologist">Cardiologist</option>
                    <option value="Dermatology">Dermatology</option>
                    <option value="Psychiatry">Psychiatry</option>
                    <option value="Nephrologists">Nephrologists</option>
                    <option value="Surgery">Surgery</option>
                </select>

                <span asp-validation-for="Specialization" class="text-danger"></span>

                @* @Html.DropDownListFor(m => m.Specialization, "Cardiologist") Cardiologist *@

            </div>
            <div class="form-group">
                <label asp-for="Experience" class="control-label"></label>
                <input asp-for="Experience" class="form-control" />
                <span asp-validation-for="Experience" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DoctorImage" class="control-label"></label>
                <input asp-for="DoctorImage" class="form-control" />
                <span asp-validation-for="DoctorImage" class="text-danger"></span>
            </div>
            @* <div class="form-group form-check">
                <label class="form-check-label">
                    <input class="form-check-input" asp-for="IsTrash" /> @Html.DisplayNameFor(model => model.IsTrash)
                </label>
            </div>
            <div class="form-group">
                <label asp-for="CreatedAt" class="control-label"></label>
                <input asp-for="CreatedAt" class="form-control" />
                <span asp-validation-for="CreatedAt" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="UpdatedAt" class="control-label"></label>
                <input asp-for="UpdatedAt" class="form-control" />
                <span asp-validation-for="UpdatedAt" class="text-danger"></span>
            </div> *@
            <br />  

            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" id="create-btn"  />
            </div>

            <br/>

            <h6>Already have a account? <a id="signin-btn" href="@Url.Action("DoctorLogin", "Doctor")">SignIn</a> </h6>

        </form>
    </div>
</div>

<div>
    @* <a asp-action="Index">Back to List</a> *@

    

</div>

HospitalManagementSystem_MVCProject/Views/Doctor/DeleteDoctor.cshtml
@model CommonLayer.Models.Doctor

@{
    ViewData["Title"] = "DeleteDoctor";
}

<link rel="stylesheet" href="~/css/DeleteUsersStyleSheet.css" asp-append-version="true" />

<h1>Delete Doctor Prifile</h1>
<hr id="hr" /> 
<br/>
<h3>Are you sure you want to delete this?</h3>
<hr />
<div id="dlt-div">
    @* <h4>Doctor</h4> *@
    
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.DoctorId)
        </dt>
        <dd class = "col-sm-10" >
            @Html.DisplayFor(model => model.DoctorId)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.FullName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.FullName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Email)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Email)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Contact)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Contact)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.DOB)
        </dt>
        <dd class = "col-sm-10">
           @*  @Html.DisplayFor(model => model.DOB) *@
            @Model.DOB
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Age)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Age)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Gender)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Gender)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Qualification)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Qualification)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Specialization)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Specialization)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Experience)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Experience)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.DoctorImage)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.DoctorImage)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.IsTrash)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.IsTrash)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.CreatedAt)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.CreatedAt)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.UpdatedAt)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.UpdatedAt)
        </dd>
    </dl>
    
    <form asp-action="DeleteDoctor" id="btns" >
        <input type="submit" value="Delete" class="btn btn-danger" id="dlt-btn" /> ||
        <a id="rd-btns" asp-action="GetAllDoctors">Back to List</a>
    </form>
</div>

HospitalManagementSystem_MVCProject/Views/Doctor/DoctorLogin.cshtml
@model CommonLayer.Models.LoginModel

@{
    ViewData["Title"] = "DoctorLogin";
}

<link rel="stylesheet" href="~/css/UserLoginStyleSheet.css" asp-append-version="true" />

<h1>Doctor Login</h1>
<hr id="hr" />
@* <h4>LoginModel</h4>
<hr /> *@
<div class="row" id="dct-lgn-div">
    <div class="col-md-4">
        <form asp-action="DoctorLogin">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                @* <label asp-for="UserId" class="control-label"></label> *@
                <input id="inp" asp-for="UserId" class="form-control" placeholder="UserId" />
                <span asp-validation-for="UserId" class="text-danger"></span>
            </div>
            <div class="form-group">
                @* <label asp-for="UserName" class="control-label"></label> *@
                <input asp-for="UserName" placeholder="UserName" class="form-control" />
                <span asp-validation-for="UserName" class="text-danger"></span>
            </div>
            <br />
            <div class="form-group">
                <input type="submit" value="Login" class="btn btn-primary" id="create-btn" />
            </div>

            <br/>

            <h6>don't' have a account? <a id="signin-btn" href="@Url.Action("AddDoctor", "Doctor")">Register</a> </h6>

        </form>
    </div>
</div>

<div>
    @*  <a asp-action="">Back to Index</a>  *@

    

</div>

HospitalManagementSystem_MVCProject/Views/Doctor/GetAllDoctors.cshtml
@model IEnumerable<CommonLayer.Models.Doctor>

@{
    ViewData["Title"] = "GetAllDoctors";
}

<h1>GetAllDoctors</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.DoctorId)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.FullName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Email)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Contact)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.DOB)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Age)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Gender)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Qualification)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Specialization)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Experience)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.DoctorImage)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.IsTrash)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.CreatedAt)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.UpdatedAt)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.DoctorId)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.FullName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Email)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Contact)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.DOB)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Age)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Gender)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Qualification)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Specialization)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Experience)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.DoctorImage)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.IsTrash)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.CreatedAt)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.UpdatedAt)
            </td>
            <td>
                    @Html.ActionLink("Edit", "UpdateDoctor", new {   patientId=item.DoctorId  }) |
                    @Html.ActionLink("Details", "GetDoctorById", new { doctorId = item.DoctorId }) |
                    @Html.ActionLink("Delete", "DeleteDoctor", new { patientId = item.DoctorId })
            </td>
        </tr>
}
    </tbody>
</table>

HospitalManagementSystem_MVCProject/Views/Doctor/GetDoctorById.cshtml
@model CommonLayer.Models.Doctor

@{
    ViewData["Title"] = "GetDoctorById";
}

<link rel="stylesheet" href="~/css/UserDetailsStyleSheet.css" asp-append-version="true" />

<h1 id="dts-title">Doctor details</h1>

<hr id="hr" />

<div id="user-dtls">
    @* <h4>Doctor</h4> *@
    @* <hr /> *@
    <dl class="row" id="container">
        <dt class = "col-sm-2" id="dct-label">
            @Html.DisplayNameFor(model => model.DoctorId)
        </dt>
        <dd class = "col-sm-10" id="dct-data">
            @Html.DisplayFor(model => model.DoctorId)
        </dd>
        <dt class="col-sm-2" id="dct-label">
            @Html.DisplayNameFor(model => model.FullName)
        </dt>
        <dd class="col-sm-10" id="dct-data">
            @Html.DisplayFor(model => model.FullName)
        </dd>
        <dt class="col-sm-2" id="dct-label">
            @Html.DisplayNameFor(model => model.Email)
        </dt>
        <dd class="col-sm-10" id="dct-data">
            @Html.DisplayFor(model => model.Email)
        </dd>
        <dt class="col-sm-2" id="dct-label">
            @Html.DisplayNameFor(model => model.Contact)
        </dt>
        <dd class="col-sm-10" id="dct-data">
            @Html.DisplayFor(model => model.Contact)
        </dd>
        <dt class="col-sm-2" id="dct-label">
            @Html.DisplayNameFor(model => model.DOB)
        </dt>
        <dd class="col-sm-10" id="dct-data">
            @* @Html.DisplayFor(model => model.DOB) *@
            @Model.DOB.ToString("d")
        </dd>
        <dt class="col-sm-2" id="dct-label">
            @Html.DisplayNameFor(model => model.Age)
        </dt>
        <dd class="col-sm-10" id="dct-data">
            @* @Html.DisplayFor(model => model.Age) *@
            @Model.Age
        </dd>
        <dt class="col-sm-2" id="dct-label">
            @Html.DisplayNameFor(model => model.Gender)
        </dt>
        <dd class="col-sm-10" id="dct-data">
            @Html.DisplayFor(model => model.Gender)
        </dd>
        <dt class="col-sm-2" id="dct-label">
            @Html.DisplayNameFor(model => model.Qualification)
        </dt>
        <dd class="col-sm-10" id="dct-data">
            @Html.DisplayFor(model => model.Qualification)
        </dd>
        <dt class="col-sm-2" id="dct-label">
            @Html.DisplayNameFor(model => model.Specialization)
        </dt>
        <dd class="col-sm-10" id="dct-data">
            @Html.DisplayFor(model => model.Specialization)
        </dd>
        <dt class="col-sm-2" id="dct-label">
            @Html.DisplayNameFor(model => model.Experience)
        </dt>
        <dd class="col-sm-10" id="dct-data">
            @Html.DisplayFor(model => model.Experience)
        </dd>
        <dt class="col-sm-2" id="dct-label">
            @Html.DisplayNameFor(model => model.DoctorImage)
        </dt>
        <dd class="col-sm-10" id="dct-data">
            @Html.DisplayFor(model => model.DoctorImage)
        </dd>
        <dt class="col-sm-2" id="dct-label">
            @Html.DisplayNameFor(model => model.IsTrash)
        </dt>
        <dd class="col-sm-10" id="dct-data">
            @Html.DisplayFor(model => model.IsTrash)
        </dd>
        <dt class="col-sm-2" id="dct-label">
            @Html.DisplayNameFor(model => model.CreatedAt)
        </dt>
        <dd class="col-sm-10" id="dct-data">
            @Html.DisplayFor(model => model.CreatedAt)
        </dd>
        <dt class="col-sm-2" id="dct-label">
            @Html.DisplayNameFor(model => model.UpdatedAt)
        </dt>
        <dd class="col-sm-10" id="dct-data">
            @Html.DisplayFor(model => model.UpdatedAt)
        </dd>

        <div id="rdct-btns">
            @* <a asp-action="Details" asp-route-id="@Model.DoctorId">Edit</a> |
            <a asp-action="GetAllDoctors">Back to List</a> *@
            @* ----- OR ----- Both works *@
            @if (Context.Session.GetInt32("DoctorId") >= 0 && Context.Session.GetInt32("PatientId") == 0)
            {
                <div id="btns">@Html.ActionLink("Update", "UpdateDoctor", new { id = Model.DoctorId })</div>
            }

            ||  <a id="btns" asp-action="GetAllDoctors">Back to list</a>  ||

            @if (Context.Session.GetInt32("PatientId") > 0)
            {
                <a id="btns" asp-controller="Appointment" asp-action="BookAppointment">Book Appointment</a>
            }

            @*  @Html.ActionLink("Edit", "Edit", new { /* id = Model.PrimaryKey */ }) |
            <a asp-action="GetAllDoctors">Back to List</a>  *@
        </div>

    </dl>
</div>

HospitalManagementSystem_MVCProject/Views/Doctor/Index.cshtml
@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>

HospitalManagementSystem_MVCProject/Views/Doctor/UpdateDoctor.cshtml
@model CommonLayer.Models.Doctor

@{
    ViewData["Title"] = "UpdateDoctor";
}

<link rel="stylesheet" href="~/css/UserDetailsUpdateStyleSheet.css" asp-append-version="true" />

<h1>Update Doctor Profile</h1>
<hr id="hr" />
 @* <h4>Doctor</h4> 
<hr /> *@
<div class="row">
    <div class="col-md-4">
        <form asp-action="UpdateDoctor">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="DoctorId" class="control-label"></label>
                <input asp-for="DoctorId" class="form-control" />
                <span asp-validation-for="DoctorId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="FullName" class="control-label"></label>
                <input asp-for="FullName" class="form-control" />
                <span asp-validation-for="FullName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Email" class="control-label"></label>
                <input asp-for="Email" class="form-control" />
                <span asp-validation-for="Email" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Contact" class="control-label"></label>
                <input asp-for="Contact" class="form-control" />
                <span asp-validation-for="Contact" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DOB" class="control-label"></label>
                <input asp-for="DOB" class="form-control" />
                <span asp-validation-for="DOB" class="text-danger"></span>
            </div>
            @* <div class="form-group">
                <label asp-for="Age" class="control-label"></label>
                <input asp-for="Age" class="form-control" />
                <span asp-validation-for="Age" class="text-danger"></span>
            </div> *@
            <div class="form-group">
                <label asp-for="Gender" class="control-label"></label>
                @* <input asp-for="Gender" class="form-control" /> *@

                <div class="form-group" id="radio-btn">
                    @Html.RadioButtonFor(m => m.Gender, "Male") Male
                    @Html.RadioButtonFor(m => m.Gender, "Female") Female
                </div>

                <span asp-validation-for="Gender" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Qualification" class="control-label"></label>
                <input asp-for="Qualification" class="form-control" />
                <span asp-validation-for="Qualification" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Specialization" class="control-label"></label>
                @* <input asp-for="Specialization" class="form-control" /> *@

                <select asp-for="Specialization" class="form-control">
                    <option hidden> --- Select ---</option>
                    <option value="Cardiologist">Cardiologist</option>
                    <option value="Dermatology">Dermatology</option>
                    <option value="Psychiatry">Psychiatry</option>
                    <option value="Nephrologists">Nephrologists</option>
                    <option value="Surgery">Surgery</option>
                </select>

                <span asp-validation-for="Specialization" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Experience" class="control-label"></label>
                <input asp-for="Experience" class="form-control" />
                <span asp-validation-for="Experience" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DoctorImage" class="control-label"></label>
                <input asp-for="DoctorImage" class="form-control" />
                <span asp-validation-for="DoctorImage" class="text-danger"></span>
            </div>
           @*  <div class="form-group form-check">
                <label class="form-check-label">
                    <input class="form-check-input" asp-for="IsTrash" /> @Html.DisplayNameFor(model => model.IsTrash)
                </label>
            </div>
            <div class="form-group">
                <label asp-for="CreatedAt" class="control-label"></label>
                <input asp-for="CreatedAt" class="form-control" />
                <span asp-validation-for="CreatedAt" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="UpdatedAt" class="control-label"></label>
                <input asp-for="UpdatedAt" class="form-control" />
                <span asp-validation-for="UpdatedAt" class="text-danger"></span>
            </div> *@
            <br/>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" id="btn" />
            </div>
            <br/>

            <div >
                <a id="btn" asp-action="GetAllDoctors">Back to List</a>
            </div>
            

        </form>
    </div>
</div>

<div>
    
</div>